services:
  # 后端服务
  backend:
    build: ./springboot
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      S3_ENDPOINT: http://pao-oss:9000
      S3_PUBLIC_ENDPOINT: http://localhost:9000
      S3_ACCESS_KEY: rustfsadmin
      S3_SECRET_KEY: rustfsadmin
    ports:
      - "8181:8181"
    depends_on:
      pao-db:
        condition: service_healthy
      pao-redis:
        condition: service_started
      pao-oss:
        condition: service_started
    volumes:
      - ./certs:/certs
    container_name: backend
    networks:
      - pao-network

  # 数据库
  pao-db:
    image: mysql:8.0.43
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: pao
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -proot --silent"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 20s
    ports:
      - "3306:3306"
    container_name: pao-db
    networks:
      - pao-network

  # redis
  pao-redis:
    image: redis:8.2.1
    ports:
      - "6379:6379"
    container_name: pao-redis
    networks:
      - pao-network

  # oss
  pao-oss:
    image: rustfs/rustfs
#    volumes:
#      - ./certs:/certs
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - RUSTFS_ACCESS_KEY=rustfsadmin
      - RUSTFS_SECRET_KEY=rustfsadmin
      - RUSTFS_TLS_PATH=/certs
      - RUSTFS_CONSOLE_ENABLE=true
    container_name: pao-oss
    networks:
      - pao-network

networks:
  pao-network:
    driver: bridge